---
exclude: '^(.*\.pem|.*\.tfvars)$'


repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      # - id: check-docstring-first # We can enable this rule once models.py is simplified
      - id: check-yaml

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        args: [--line-length=100]

  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint
        # We didn't write codecov.sh, we just get it from their servers
        # The other one is a template.
        exclude: "codecov.sh|infrastructure/workers-configuration/client-instance-user-data.tpl.sh"
        args:
            # SC2154: Exclude warnings about variables being used without being
            #         assigned, because we sometimes use lowercase environment
            #         variables which shellcheck does not recognize.
            # SC1090,SC1091: Don't try to follow sourced files
          - --exclude=SC2154,SC1090,SC1091

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.45.0
    hooks:
      - id: terraform_validate
        # It's a small file that gets copied up temporarily during deploys.
        # Because it's not where it gets run it seems to be in a module when it's not.
        exclude: "infrastructure/deploy/ci_ingress.tf"
