name: workers
dependencies:
  - r::r-base=3.3.1
  - greenelab::all-entrezg-brainarray-cdfs
  - kurtwheeler::bioconductor-pd.hugene.1.0.st.v1
  - kurtwheeler::bioconductor-pd.hg.u95av2
  - bioconda::bioconductor-oligo
  - bioconda::bioconductor-biobase
  - bioconda::bioconductor-scan.upc
  - bioconda::bioconductor-affy=1.50.0
  - bioconda::bioconductor-affyio=1.42.0
  - bioconda::bioconductor-annotationdbi=1.36.2
  - bioconda::bioconductor-org.hs.eg.db=3.3.0
  - bioconda::bioconductor-org.mm.eg.db=3.4.0
  - bioconda::bioconductor-org.dm.eg.db=3.4.0
  - bioconda::bioconductor-org.ce.eg.db=3.2.3
  - bioconda::r-ff
  - python=3.6
  - r::rpy2=2.8.5
  - pycurl=7.43.0
  - pip:
    - celery==4.0.2
    - django==1.10.6
    - requests==2.13.0
    - psycopg2==2.7.1
    - boto3==1.4.4
    - retrying==1.3.3
